database-system-api.hostname=${ext.database-system-api.hostname}
database-system-api.port=${ext.database-system-api.port}
google-maps-system-api.hostname=${ext.google-maps-system-api.hostname}
google-maps-system-api.port=${ext.google-maps-system-api.port}
square-system-api.hostname=${ext.square-system-api.hostname}
square-system-api.port=${ext.square-system-api.port}
push-notifications-system-api.hostname=${ext.push-notifications-system-api.hostname}
push-notifications-system-api.port=${ext.push-notifications-system-api.port}
