#%RAML 1.0
title: Square

baseUri: /square/v1

/payment-links:
  post:
    body:
      application/json:
        properties:
          description: 
            type: string
          amount:
            type: number
          currency:
            type: string
          

/orders:

/refunds:


  