# Downstream APIs
database-system-api.hostname=${ext.database-system-api.hostname}
database-system-api.port=${ext.database-system-api.port}
okta-system-api.hostname=${ext.okta-system-api.hostname}
okta-system-api.port=${ext.okta-system-api.port}
email-system-api.hostname=${ext.email-system-api.hostname}
email-system-api.port=${ext.email-system-api.port}
square-system-api.hostname=${ext.square-system-api.hostname}
square-system-api.port=${ext.square-system-api.port}
background-check-system-api.hostname=${ext.background-check-system-api.hostname}
background-check-system-api.port=${ext.background-check-system-api.port}
