# Postgres
postgres.hostname=${ext.postgres.hostname}
postgres.port=${ext.postgres.port}
postgres.service=${ext.postgres.service}
postgres.username=${ext.postgres.username}
postgres.password=${ext.postgres.password}
