#%RAML 1.0 Library
usage:

uses:
  commons: exchange_modules/e23e734a-7f55-4852-8d8d-fb70ad146ecd/common-data-types-libraries/1.0.0/common-data-types-library.raml

types:
  ride:
    type: object
    description:
    properties:
      id?: commons.idType
      rate?: number
      pickupLocation?:
      destination?:
      destinationName?:
      createdDate?:
      lastModifiedDate?:
      status?: rideStatus

  rideSummary:
    type: object
    description:
    properties:
      id?:
      rate:
      pickupLocation:
      destination:
      destinationName:
      status:
      route:
        type: route
      passenger:
        type: object
        properties:
          firstName:
          profilePicture:
          rating: number
      driver:
        type: object
        properties:
          firstName:
          profilePicture:
          rating: number
      lastModifiedDate:
      createdDate:

  location:
    type: object
    properties:
      long: number
      lat: number
      name:
      zipCode:

  route:
    type: object
    properties:
      ToDo: string

  rideParticipant:
    type: object
    description: 
    properties:
      firstName:
      profilePicture:
      rating: number

  rideStatus:
    enum:
      - NEW
      - WAITING_FOR_DRIVER
      - DRIVING_TO_PASSENGER_LOCATION
      - WAITING_FOR_PASSANGER
      - CANCELED_FOR_REFUND
      - CANCELED_WITHOUT_REFUND
      - PASSENGER_GETS_INTO_THE_CAR
      - IN_ROUTE
      - ARRIVED_AT_DESTINATION
      - FINISHED
      - ACCEPTED_BY_DRIVER