#%RAML 1.0 Trait

uses:
  commons: exchange_modules/e23e734a-7f55-4852-8d8d-fb70ad146ecd/common-data-types-library/1.0.0/common-data-types-library.raml

responses:
  400:
    description: Bad request    
  401:
    description: Unauthorized Access
    body:
      type: commons.apiResponse
  403:
    description: Not Authorized
    body:
      type: commons.apiResponse
  404:
    description: Not found
  405:
    description: Method not allowed
    body:
      type: commons.apiResponse    
  408:
    description: Request timeout
  409:
    description: Entity already exists
  413:
    description: Payload too large
    body:
      type: commons.apiResponse
  429:
    description: Too many requests
  500:
    description: Internal server error
    body:
      type: commons.apiResponse