#%RAML 1.0
title: Square

types:
  orders: !include types/orders.raml
  orderFulfillment: !include types/orderFulfillment.raml
  paymentLink: !include types/paymentLink.raml
  paymentLinkResponse: !include types/paymentLinkResponse.raml
/payments:
  /link:
    post:
      body:
        application/json:
          type: paymentLink
          example: !include examples/paymentLink.json
      responses:
        200:
          body:
            application/json:
              type: paymentLinkResponse
              example: !include examples/paymentLinkResponse.json

/orders:
  /{orderId}:
    get:
      responses:
        200:
          body:
            application/json:
              type: orders
              example: !include examples/orders.json
    put:
      body:
        application/json:
          type: orderFulfillment
          example: !include examples/orderFulfillment.json
      responses:
        200:
          body:
            application/json:
              properties:                
                message:
                  type: string
                  example: "Success"
          
      


    