# RabbitMQ
rabbitmq.hostname=${ext.rabbitmq.hostname}
rabbitmq.port=${ext.rabbitmq.port}
rabbitmq.virtualhost=${ext.rabbitmq.virtualhost}
rabbitmq.username=${ext.rabbitmq.username}
rabbitmq.password=${ext.rabbitmq.password}

# Google Maps
googlemaps.hostname=${ext.googlemaps.hostname}
googlemaps.port=${ext.googlemaps.port}
googlemaps.key=${ext.googlemaps.key}

# Okta
okta.hostname=${ext.okta.hostname}
okta.port=${ext.okta.port}

# Square
square.hostname=${ext.square.hostname}
square.port=${ext.square.port}

# Downstream APIs
database-system-api.hostname=${ext.database-system-api.hostname}
database-system-api.port=${ext.database-system-api.port}
user-sign-up-process-api.hostname=${ext.user-sign-up-process-api.hostname}
user-sign-up-process-api.port=${ext.user-sign-up-process-api.port}
request-ride-process-api.hostname=${ext.request-ride-process-api.hostname}
request-ride-process-api.port=${ext.request-ride-process-api.port}
cancel-ride-process-api.hostname=${ext.cancel-ride-process-api.hostname}
cancel-ride-process-api.port=${ext.cancel-ride-process-api.port}
driver-availability-process-api.hostname=${ext.driver-availability-process-api.hostname}
driver-availability-process-api.port=${ext.driver-availability-process-api.port}
salesforce-system-api.hostname=${ext.salesforce-system-api.hostname}
salesforce-system-api.port=${ext.salesforce-system-api.port}
