name: Push Design Center Projects
run-name: Push updates to Design Center run by ${{ github.actor }}
on:
  workflow_dispatch:

jobs:
  push-to-design-center:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node JS
        uses: actions/setup-node@v4
        with:
          node-version: '21'
      - name: Install Anypoint CLI v4
        run: npm install -g anypoint-cli-v4
      - name: Install Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Install Maven 3.9.8
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.9.8'
      - run: echo "Setup completed"
      - name: Upload Design Center Projects
        env:
          ANYPOINT_ORG: ${{ vars.ANYPOINT_ORG }}
          ANYPOINT_ENV: ${{ vars.ANYPOINT_ENV }}
          ANYPOINT_CLIENT_ID: ${{ secrets.ANYPOINT_CLIENT_ID }}
          ANYPOINT_CLIENT_SECRET: ${{ secrets.ANYPOINT_CLIENT_SECRET }}
          GH_TOKEN: ${{ github.token }}
        run: |
          PROJECT_FOLDER=user-data-type
          DESIGN_CENTER_PROJECT_NAME=$(jq -r '.name' design-center/$PROJECT_FOLDER/exchange.json)
          DESIGN_CENTER_PROJECT_TYPE=$(jq -r '.classifier' design-center/$PROJECT_FOLDER/exchange.json)
          EXCHANGE_GROUP_ID=$(jq -r '.groupId' design-center/$PROJECT_FOLDER/exchange.json)
          EXCHANGE_ASSET_ID=$(jq -r '.assetId' design-center/$PROJECT_FOLDER/exchange.json)
          EXCHANGE_ASSET_VERSION=$(jq -r '.version' design-center/$PROJECT_FOLDER/exchange.json)
          EXCHANGE_API_VERSION=v1
          EXCHANGE_MAIN_FILE=$(jq -r '.main' design-center/$PROJECT_FOLDER/exchange.json)
          
          if [ $DESIGN_CENTER_PROJECT_TYPE = "raml" ]; then
            EXCHANGE_ASSET_TYPE=rest-api
          else
            EXCHANGE_ASSET_TYPE=$DESIGN_CENTER_PROJECT_TYPE
          fi
          
          cd design-center/$PROJECT_FOLDER; 
          #rm exchange.json; 
          #rm -rf exchange_modules; zip -r raml.zip *; mv raml.zip ../../; cd ../../
          
          #echo "Creating \"$DESIGN_CENTER_PROJECT_NAME\" in Design Center"
          #anypoint-cli-v4 designcenter:project:create --type "$DESIGN_CENTER_PROJECT_TYPE" --fragmentType library "$DESIGN_CENTER_PROJECT_NAME"
          #echo "Uploading \"$DESIGN_CENTER_PROJECT_NAME\" to Design Center"
          #anypoint-cli-v4 designcenter:project:upload "$DESIGN_CENTER_PROJECT_NAME" design-center/$PROJECT_FOLDER
          #echo "Uploading $EXCHANGE_GROUP_ID/$EXCHANGE_ASSET_ID/$EXCHANGE_ASSET_VERSION $EXCHANGE_ASSET_TYPE to Exchange"
          #anypoint-cli-v4 exchange:asset:upload --name "$DESIGN_CENTER_PROJECT_NAME" --type "$EXCHANGE_ASSET_TYPE" --status "development" --properties="{\"mainFile\": \"$EXCHANGE_MAIN_FILE\", \"apiVersion\": \"v1\", \"classifier\":\"raml-fragment\",  \"type\":\"raml-fragment\"}" --files="{\"raml.zip\": \"raml.zip\"}" "$EXCHANGE_GROUP_ID/$EXCHANGE_ASSET_ID/$EXCHANGE_ASSET_VERSION"
          curl --location --request POST 'https://anypoint.mulesoft.com/accounts/login' --header 'Content-Type: application/json' --header 'Accept: application/json' --data-raw '{ "username":"~~~Client~~~", "password":"${ANYPOINT_CLIENT_ID}~?~${ANYPOINT_CLIENT_SECRET}" }'
