name: Setup
run-name: Setup Action run by ${{ github.actor }}
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node JS
        uses: actions/setup-node@v4
        with:
          node-version: '21'
      - name: Install Anypoint CLI v4
        run: npm install -g anypoint-cli-v4
      - run: echo $ANYPOINT_ORG
      - run: anypoint-cli-v4 --version
      - name: Install Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
      - run: java -version
      - name: Install Maven 3.9.8
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.9.8'
      - run: mvn -B -version
      - run: mvn -B help:effective-settings
      - run: echo "Setup completed"
