name: GitHub Actions Mule
run-name: Syncronization from Design Center Action run by ${{ github.actor }}
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node JS
        uses: actions/setup-node@v4
        with:
          node-version: '21'
      - name: Install Anypoint CLI v4
        run: npm install -g anypoint-cli-v4
      - name: Download Design Center Projects
        env:
          ANYPOINT_ORG: ${{ vars.ANYPOINT_ORG }}
          ANYPOINT_ENV: ${{ vars.ANYPOINT_ENV }}
          ANYPOINT_CLIENT_ID: ${{ secrets.ANYPOINT_CLIENT_ID }}
          ANYPOINT_CLIENT_SECRET: ${{ secrets.ANYPOINT_CLIENT_SECRET }}
        run: |
          mkdir -p design-center
          anypoint-cli-v4 designcenter:project:list --output json --pageSize 1000 | jq -c '.[]' | while read -r PROJECT
          do
            PROJECT_NAME=$(echo $PROJECT | jq -r '.name')
            echo $PROJECT
            echo "Downloading $PROJECT_NAME"
            anypoint-cli-v4 designcenter:project:download "$PROJECT_NAME" ./design-center
          done
          ls -l ./design-center
