name: GitHub Actions Mule
run-name: Syncronization from Design Center Action run by ${{ github.actor }}
on: 
  workflow_dispatch:
      inputs:          
          api-name:
            description: 'API name to update'
            required: true
            default: ''
          api-impl-folder:
            description: 'API Implementation folder name to update'
            required: true
            default: ''

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node JS
        uses: actions/setup-node@v4
        with:
          node-version: '21'
      - name: Install Anypoint CLI v4
        run: npm install -g anypoint-cli-v4      
      - run: echo "Setup completed"
      - run: mkdir -p ./${{inputs.api-impl-folder}}/src/main/resources/api
      - name: Download Design Center Projects
        env:
          ANYPOINT_ORG: ${{ vars.ANYPOINT_ORG }}
          ANYPOINT_ENV: ${{ vars.ANYPOINT_ENV }}
          ANYPOINT_CLIENT_ID: ${{ secrets.ANYPOINT_CLIENT_ID }}
          ANYPOINT_CLIENT_SECRET: ${{ secrets.ANYPOINT_CLIENT_SECRET }}
        run: anypoint-cli-v4 designcenter:project:download ${{inputs.api-name}} ${{inputs.api-impl-folder}}/src/main/resources/api
      - name: Check for differences
        id: git_diff
        run: |
          if git diff --quiet; then echo "diff=0" >> $GITHUB_OUTPUT; else echo "diff=1" >> $GITHUB_OUTPUT ; fi
      - name: Create branch, commit and create a PR
        id: cpr
        uses: peter-evans/create-pull-request@v6
        if: ${{ steps.git_diff.outputs.diff }} != 0
        with:
          commit-message: An update on the Design Center API Definition was detected for the ${{inputs.api-name}} project.
          title: Changes on ${{inputs.api-name}} on Design Center
          body: |
            - API Definition Updated
            
            Auto-generated by [create-pull-request][1]

          branch: design-center-update-${{ inputs.api-name }}-${{ github.run_id }}
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"