rabbitmq.hostname=${ext.rabbitmq.hostname}
rabbitmq.port=${ext.rabbitmq.port}
rabbitmq.virtualhost=${ext.rabbitmq.virtualhost}
rabbitmq.username=${ext.rabbitmq.username}
rabbitmq.password=${ext.rabbitmq.password}
request-ride-process-api.hostname=${ext.request-ride-process-api.hostname}
request-ride-process-api.port=${ext.request-ride-process-api.port}
database-system-api.hostname=${ext.database-system-api.hostname}
database-system-api.port=${ext.database-system-api.port}
